# Generated by Django 5.0.6 on 2024-06-11 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a musician name', max_length=64)),
                ('description', models.TextField(help_text='Enter a description')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Enter a username', max_length=128)),
                ('password', models.CharField(help_text='Enter a password', max_length=64)),
                ('email', models.EmailField(help_text='Enter an email address', max_length=128)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a music name', max_length=64)),
                ('album', models.CharField(help_text='Enter a album name', max_length=64)),
                ('genre', models.CharField(help_text='Enter a genre', max_length=64)),
                ('release_date', models.DateField()),
                ('path', models.CharField(max_length=128)),
                ('artist', models.ManyToManyField(to='backend.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a playlist name', max_length=64)),
                ('descrption', models.TextField(default='', help_text='Enter a description')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='follower',
            field=models.ManyToManyField(to='backend.user'),
        ),
        migrations.CreateModel(
            name='PlaylistContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.music')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.playlist')),
            ],
            options={
                'unique_together': {('playlist', 'music')},
            },
        ),
    ]
