# Generated by Django 5.0.6 on 2024-06-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_descrption_playlist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='password',
            field=models.CharField(default='', help_text='Enter a password', max_length=64),
        ),
    ]
