# Generated by Django 5.0.6 on 2024-06-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_artist_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='follower',
        ),
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(blank=True, to='backend.artist'),
        ),
    ]
