# Generated by Django 5.0.6 on 2024-06-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.CharField(default='', help_text='Enter a genre', max_length=64),
        ),
    ]
