# Generated by Django 5.0.6 on 2024-06-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_artist_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(blank=True, to='backend.artist'),
        ),
    ]
